### ISSUE TITLE
SSL issues in Python 2.7.9

### ISSUE THREAD

**Issue by tweigel-vaisala** [Qumulo/python_scripts#3]
I am pretty sure this issue should be filed with the /qumulo/ library, rather than with scripts built on top of it, but I'm not sure where to go for that.

Python 2.7.9 backports a very helpful httplib.HTTPSConnection behavior from Python 3 (checking the SSL certificate). On most systems this is probably not a problem, but our qumulo server has a self-signed certificate which is failing the certificate verification.

I think the most probable cause is described here: https://github.com/mtschirs/quizduellapi/issues/2

(The monkey patch suggested in that discussion works, but smells bad. I haven't spent any time digging into alternatives, yet.)

Most of our systems have not upgraded to 2.7.9 yet, but that is just a matter of time. And while I have not tested it in any python 3 systems, given that this is a backport, I would expect similar behavior. Below is the simplest-case stack trace:

```bash
$ ./version_request.py --host grendel.reit3 --user admin --port 8000
VERSION:
Traceback (most recent call last):
  File "./version_request.py", line 139, in <module>
    main()
  File "./version_request.py", line 131, in main
    print "VERSION: ", qumulo.rest.version.version(conninfo, None)
  File "/usr/local/lib/python2.7/dist-packages/qumulo/rest/version.py", line 20, in version
    return request.rest_request(conninfo, credentials, method, uri)
  File "/usr/local/lib/python2.7/dist-packages/qumulo/lib/request.py", line 451, in rest_request
    rest.send_request()
  File "/usr/local/lib/python2.7/dist-packages/qumulo/lib/request.py", line 308, in send_request
    self.conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/qumulo/lib/request.py", line 82, in connect
    return httplib.HTTPSConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 1269, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by tweigel-vaisala** [comment]
Replace 'grendel.reit3' above with whatever hostname you're using, of course :-)

**Comment by FreeAssoc** [comment]
Hi @tweigel-vaisala - 

I'm using python 2.7.10 via virtualenv and this does not repro for me:

```
(py27)➜  python_scripts git:(master) ./version_request.py --host dev --port 20095
VERSION:  {
    "build_date": "2015-06-04T20:46:05Z",
    "build_id": "43067.mmurray",
    "revision_id": "Qumulo Core 1.2.7"
}
```

One of our SE's had a very similar problem last week when he pointed at a node with an older version of the API server running -- could that be the case here as well?  Pls let me know.

thanks - Michael

**Comment by tweigel-vaisala** [comment]
python 2.7.9 (as noted above) and
``` JSON
{
    "revision_id": "Qumulo Core 1.2.6",
    "build_id": "42411.1.38",
    "build_date": "2015-06-11T20:31:27Z"
}
```
(which is the latest *released* build, so far as I am aware.)

If API 1.2.7 fixes the issue, then this is a non-issue to me. As soon as it is released and we've upgraded, this problem goes away.

If python 2.7.10 fixes the issue (certificate verification fixes are in the changelog, at least), then this is still an issue for me. Although worst case, I suppose I could just make a note that Qumulo is compatible with python 2.7.[6-8,10], and push internally to avoid using 2.7.9.

I will try to test 2.7.10 with 1.2.6 sometime soon.

**Comment by FreeAssoc** [comment]
OK I'll try to find a 1.2.6 environment internally and if I can repro this...

**Comment by tweigel-vaisala** [comment]
If you can reproduce it on 1.2.6, then 1.2.7 probably fixes it:
```bash
tweigel@oceana:~/git/qpy$ python -V
Python 2.7.10
tweigel@oceana:~/git/qpy$ ./version_request.py --host grendel.reit3 --user tweigel --port 8000
VERSION:
Traceback (most recent call last):
  File "./version_request.py", line 139, in <module>
    main()
  File "./version_request.py", line 131, in main
    print "VERSION: ", qumulo.rest.version.version(conninfo, None)
  File "/usr/local/lib/python2.7/site-packages/qumulo/rest/version.py", line 20, in version
    return request.rest_request(conninfo, credentials, method, uri)
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 451, in rest_request
    rest.send_request()
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 308, in send_request
    self.conn.connect()
  File "/usr/local/lib/python2.7/site-packages/qumulo/lib/request.py", line 82, in connect
    return httplib.HTTPSConnection.connect(self)
  File "/usr/local/lib/python2.7/httplib.py", line 1274, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
tweigel@oceana:~/git/qpy$
```
